[default]
address = "0.0.0.0"

[default.databases.sea_orm]
url = "mysql://root@localhost/group"

# [development]
# databases = { sea_orm = {url = "mysql://root:group@db/group"} }
# url = "mysql://root:group@db/group"